name: Upload docker containers

on:
  workflow_dispatch:
  push:
    paths:
      - 'tf_sig_build_dockerfiles/**'
      - '!tf_sig_build_dockerfiles/README.md'
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [python3.6, python3.7, python3.8, python3.9]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout TensorFlow to get the current version
        uses: actions/checkout@v2
        with:
          repository: tensorflow/tensorflow
          path: tensorflow
          fetch-depth: 1
      -
        name: Grab the upcoming TF version to tag this container
        run: |
          minor_version=$(grep "^#define TF_MINOR_VERSION" tensorflow/core/public/version.h | grep -o "[[:digit:]])"
          major_version=$(grep "^#define TF_MAJOR_VERSION" tensorflow/core/public/version.h | grep -o "[[:digit:]])"
          echo ::set-output name=TF_VERSION::${TF_MAJOR_VERSION}.${TF_MINOR_VERSION}
        id: tf-version
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./tf_sig_build_dockerfiles
          target: devel
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
          tags: |
            tensorflow/build:latest-${{ matrix.python-version }}
            tensorflow/build:${{ steps.tf-version.outputs.TF_VERSION }}-${{ matrix.python-version }}
          cache-from: type=registry,ref=tensorflow/build:latest-${{ matrix.python-version }}
          cache-to: type=inline
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

