# Containers go to angersson/tensorflow-build to avoid polluting the
# TensorFlow namespace until we're sure these are useful.
name: Upload docker containers

on:
  workflow_dispatch:
  push:
    paths:
      - 'official_build_environments/**'
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [python3.6, python3.7, python3.8, python3.9]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./official_build_environments/master/linux
          target: devel
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
          tags: angersson/tensorflow-build:latest-${{ matrix.python-version }}
          cache-from: type=registry,ref=angersson/tensorflow-build:latest-${{ matrix.python-version }}
          cache-to: type=inline
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

