name: Upload requested containers to gcr.io

on:
  pull_request:
    types: [labeled]
    paths:
      - '.github/workflows/docker-gcr.yml'
      - 'tf_sig_build_dockerfiles/**'
      - '!tf_sig_build_dockerfiles/README.md'

jobs:
  docker:
    if: ${{ github.event.label.name == 'build and push to gcr.io for staging' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [python3.7, python3.8, python3.9]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Clear the build-and-push label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: build and push to gcr.io for staging
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_CREDS }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./tf_sig_build_dockerfiles
          target: devel
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
          tags: |
            gcr.io/tensorflow-sigs/build:${{ github.event.number }}-${{ matrix.python-version }}
          cache-from: |
            type=registry,ref=tensorflow/build:latest-${{ matrix.python-version }}
            type=registry,ref=gcr.io/tensorflow-sigs/build:${{ github.event.number }}-${{ matrix.python-version }}
          cache-to: type=inline
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  comment:
    if: ${{ github.event.label.name == 'build and push to gcr.io for staging' }}
    runs-on: ubuntu-latest
    needs: docker
    steps:
      -
        name: Add a comment with the pushed containers
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Pushed these containers:
            - `gcr.io/tensorflow-sigs/build:${{ github.event.number }}-python3.9`
            - `gcr.io/tensorflow-sigs/build:${{ github.event.number }}-python3.8`
            - `gcr.io/tensorflow-sigs/build:${{ github.event.number }}-python3.7`

