name: Upload docker containers

on: [pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [python3.7, python3.8, python3.9]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./experimental_official_dockerfiles/master
          target: devel
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
          tags: angersson/tensorflow-build:latest-${{ matrix.python-version }}
          # cache-from: type=registry,ref=angersson/tensorflow-build:latest-${{ matrix.python-version }}
          cache-from: type=registry,ref=angersson/tensorflow-build:latest
          cache-to: type=inline
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

